### ISSUE TITLE
Unraid Setup

### ISSUE THREAD

**Issue by Tmatz27** [Kometa-Team/ImageMaid#63]
### Version Number

develop

### What branch are you on?

develop

### Describe the Bug

I can not get the docker in unraid to run. It states there is noplex URL, plex token, and the plex path are present so its running in local mode. But the .env has those valuses present. Not sure what I need to do to fix this. 
![Screenshot 2024-07-11 113014](https://github.com/Kometa-Team/ImageMaid/assets/116435680/ff14c6ba-6044-487e-9f4e-c5ef9f83d23e)

**Comment by Tmatz27** [comment]
Made a little more head way but still having issues. Its now saying that it sees plex is running. ive restarted Plex before starting the docker, and I have even changed the ignore if running variable to True and it still wont start. 
![Screenshot 2024-07-11 153101](https://github.com/user-attachments/assets/58e5c9d4-156c-4ee8-81f7-cfd0fd52aa99)

**Comment by gehrleib** [comment]
Add "IGNORE_RUNNING=True" as it states in the Error Report.

I also added "LOCAL_DB=True" as it was failing to pull it from the API

**Comment by Tmatz27** [comment]
I have ignore running=true in the .env initially it really seems like it's not even looking at the .env

**Comment by jerry00020001** [comment]
I am having the same issue. It's not seeing the env file

**Comment by jerry00020001** [comment]
I figured it out, @Tmatz27 , the .env literally has to be named '.env' 

I had mine as test.env , then tried example.env , but it's just .env

**Comment by Tmatz27** [comment]
My file was already named .env and still having the issue

**Comment by Lebowski89** [comment]
I see this issue is still open. Have you worked it out? Just installed this for the first time on UnRaid (7.0.0-rc.1) without any issues. Make sure you create an '.env' file in the config directory. Contents will look like:

```
PLEX_PATH=/plex
MODE=report
SCHEDULE=
PLEX_URL=http://<Machine IP>:32400
PLEX_TOKEN=yourtokenhere
DISCORD=
TIMEOUT=600
SLEEP=60
IGNORE_RUNNING=False
LOCAL_DB=False
USE_EXISTING=False
PHOTO_TRANSCODER=True
EMPTY_TRASH=True
CLEAN_BUNDLES=True
OPTIMIZE_DB=True
TRACE=True
LOG_REQUESTS=True
```

```
|======================================== Validating Options ========================================|
| Running in Move Mode with Empty Trash, Clean Bundles, Optimize DB, and PhotoTrancoder set to True  |
| Move: Metadata Directory Files will be moved to the ImageMaid Restore Directory. (CAN BE RESTORED) |
| Connecting To Plex                                                                                 |
| Starting new HTTP connection (1): 192.168.80.20:32400                                              |
| http://192.168.80.20:32400 "GET / HTTP/11" 200 4687                                                |
| Successfully Connected to Plex
```

**Comment by Tmatz27** [comment]
I already had the file named .env but i think i worked it out, I think there was an error with the plex path. I reinstalled imagemaid and redid the whole path and I think I finally got it to work. now when I look at the logs it just shows when I have it scheduled to run. no errors

**Comment by Tmatz27** [comment]
ive got it working

**Comment by Tmatz27** [comment]
I got it working
